add new error for disabled service, with test
google-gemini/generative-ai-android pull request #148
Opened 2024-05-15 20:51 UTC by davidmotson

2024-05-15 21:11 UTC, rlazo approved these changes

2024-05-15 21:11 UTC, rlazo commented on common/src/main/kotlin/com/google/ai/client/generativeai/common/APIController.kt
> +      "Firebase ML API has not been used in project .* before or it is disabled".toRegex()
```suggestion
      "Firebase ML API has not been used in project"
```

2024-05-15 21:11 UTC, rlazo commented on common/src/main/kotlin/com/google/ai/client/generativeai/common/APIController.kt
> +      "Firebase ML API has not been used in project .* before or it is disabled".toRegex()
if we match a bit less, I think it's going to work as intended and will do away with regexp. ptal

2024-05-15 21:58 UTC, andrewheard commented on common/src/test/resources/golden-files/unary/failure-service-disabled.json
> +      }
If not too much trouble, I would recommend parsing the [`ErrorInfo`](https://cloud.google.com/apis/design/errors#error_info) and looking for `SERVICE_DISABLED` in [`reason`](https://github.com/googleapis/googleapis/blob/ab4ba823439f786b2091984fed6408a950aaef9e/google/rpc/error_details.proto#L52-L57) and checking if `service` is `firebaseml.googleapis.com` in [`metadata`](https://github.com/googleapis/googleapis/blob/ab4ba823439f786b2091984fed6408a950aaef9e/google/rpc/error_details.proto#L67-L75).

The `message` isn't guaranteed to remain the same but the other values should be constants that we can rely on. This would be less brittle than a regex, IMHO.

2024-05-16 13:48 UTC, rlazo requested changes
+1 to andrew's comment

2024-05-16 22:10 UTC, rlazo commented on common/src/main/kotlin/com/google/ai/client/generativeai/common/APIController.kt
> +  if (error.error.details.any { "SERVICE_DISABLED" == it.reason }) {
```suggestion
  if (error.error.details.any { it.reason == "SERVICE_DISABLED"  }) {
```

2024-05-16 22:11 UTC, rlazo commented on common/src/main/kotlin/com/google/ai/client/generativeai/common/APIController.kt
> +      JSON.decodeFromString<GRpcErrorResponse>(text)
```suggestion
      JSON.decodeFromString<GRpcErrorResponse>(text).error
```

2024-05-21 21:32 UTC, rlazo approved these changes

2024-05-21 21:34 UTC, andrewheard approved these changes

2024-05-21 21:51 UTC, rlazo commented
We probably also want to match swift's error message

https://github.com/firebase/firebase-ios-sdk/pull/13007

2024-05-22 17:00 UTC, davidmotson commented
The error message from the serverside contains the link to fix the issue, and is passed along to the customer

2024-05-22 17:58 UTC, rlazo approved these changes

2024-05-22 18:01 UTC, merged