Add documentation snippets to the repo
google-gemini/generative-ai-android pull request #182
Opened 2024-06-13 22:10 UTC by rlazo

2024-06-23 16:56 UTC, rachelsaunders requested changes

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  // [START chat_with-images_streaming]
```suggestion
  // [START chat_streaming_with_images]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  // [START chat_with-images_streaming]
Since we're using these labels as the region tags rather than file names, we can't use hyphens (only underscores).

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  // [END chat_with-images_streaming]
```suggestion
  // [END chat_streaming_with_images]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +  // [START tokens_text-only]
```suggestion
  // [START tokens_text_only]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +  // [END tokens_text-only]
```suggestion
  // [END tokens_text_only]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +          // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +          // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +          // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +          // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +          // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +  // [START tokens_multimodal-image_inline]
```suggestion
  // [START tokens_multimodal_image_inline]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +          // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +  // [START tokens_multimodal-image_inline]
```suggestion
  // [START tokens_multimodal_image_inline]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  // [START chat]
**QUESTION**

Do we want to start each region tag before the `suspend` function line?

We mention in the dev docs that calls like `generateContent` are suspend functions, but do we need to make it more explicit in the snippet displayed in the dev docs?  I think for devs proficient with Android development, this is obvious, but I just wanted to check on y'all's thoughts.

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +    // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +    // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +    // [START chat_with-images_streaming]
```suggestion
    // [START chat_streaming_with_images]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +    // The Gemini 1.5 models are versatile and work with multi-turn conversations (like chat)
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +    // [END chat_with-images_streaming]
```suggestion
    // [END chat_streaming_with_images]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +          // [START_EXCLUDE]
**QUESTION**

Is this meant to be a region tag?  Here and below?

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/count_tokens.java
> +    // [START tokens_text-only]
```suggestion
    // [START tokens_text_only]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/count_tokens.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/count_tokens.java
> +    // [END tokens_text-only]
```suggestion
    // [END tokens_text_only]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/count_tokens.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/count_tokens.java
> +      // [START tokens_multimodal-image_inline]
```suggestion
      // [START tokens_multimodal_image_inline]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/count_tokens.java
> +    // [END tokens_multimodal-image_inline]
```suggestion
    // [END tokens_multimodal_image_inline]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/count_tokens.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/model_configuration.java
> +    // The Gemini 1.5 models are versatile and work with most use cases
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/safety_settings.java
> +    // [START safety-settings]
```suggestion
    // [START safety_settings]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/safety_settings.java
> +    // The Gemini 1.5 models are versatile and work with most use cases
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/safety_settings.java
> +    // [END safety-settings]
```suggestion
    // [END safety_settings]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/safety_settings.java
> +    // [START safety-settings_multi]
```suggestion
    // [START safety_settings_multi]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/safety_settings.java
> +    // The Gemini 1.5 models are versatile and work with most use cases
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/safety_settings.java
> +    // [END safety-settings_multi]
```suggestion
    // [END safety_settings_multi]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/system_instructions.java
> +            /* modelName */ "gemini-1.5-flash",
```suggestion
            // Specify a Gemini model appropriate for your use case
            /* modelName */ "gemini-1.5-flash",
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [START text_gen_text-only-prompt]
```suggestion
    // [START text_gen_text_only_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_text-only-prompt]
```suggestion
    // [END text_gen_text_only_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [START text_gen_text-only-prompt_streaming]
```suggestion
    // [START text_gen_text_only_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_text-only-prompt_streaming]
```suggestion
    // [END text_gen_text_only_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [START text_gen_multimodal-one-image-prompt]
```suggestion
    // [START text_gen_multimodal_one_image_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_multimodal-one-image-prompt]
```suggestion
    // [END text_gen_multimodal_one_image_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [START text_gen_multimodal-one-image-prompt_streaming]
```suggestion
    // [START text_gen_multimodal_one_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_multimodal-one-image-prompt_streaming]
```suggestion
    // [END text_gen_multimodal_one_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_multimodal-multi-image-prompt]
```suggestion
    // [END text_gen_multimodal_multi_image_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [START text_gen_multimodal-multi-image-prompt_streaming]
```suggestion
    // [START text_gen_multimodal_multi_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
    // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_multimodal-multi-image-prompt_streaming]
```suggestion
    // [END text_gen_multimodal_multi_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [START text_gen_multimodal-video-prompt]
```suggestion
    // [START text_gen_multimodal_video_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_multimodal-video-prompt]
```suggestion
    // [END text_gen_multimodal_video_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [START text_gen_multimodal-video-prompt_streaming]
```suggestion
    // [START text_gen_multimodal_video_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/text_generation.java
> +    // [END text_gen_multimodal-video-prompt_streaming]
```suggestion
    // [END text_gen_multimodal_video_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/model_configuration.kt
> +          // The Gemini 1.5 models are versatile and work with most use cases
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/safety_settings.kt
> +          // The Gemini 1.5 models are versatile and work with most use cases
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/safety_settings.kt
> +  // [START safety-settings_multi]
```suggestion
  // [START safety_settings_multi]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/safety_settings.kt
> +  // [END safety-settings_multi]
```suggestion
  // [END safety_settings_multi]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/system_instructions.kt
> +          modelName = "gemini-1.5-flash",
```suggestion
          // Specify a Gemini model appropriate for your use case
          modelName = "gemini-1.5-flash",
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_text-only-prompt]
```suggestion
  // [START text_gen_text_only_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +          // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_text-only-prompt]
```suggestion
  // [END text_gen_text_only_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_text-only-prompt_streaming]
```suggestion
  // [START text_gen_text_only_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +          // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_text-only-prompt_streaming]
```suggestion
  // [END text_gen_text_only_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_multimodal-one-image-prompt]
```suggestion
  // [START text_gen_multimodal_one_image_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +          // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_multimodal-one-image-prompt]
```suggestion
  // [END text_gen_multimodal_one_image_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_multimodal-one-image-prompt_streaming]
```suggestion
  // [START text_gen_multimodal_one_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +          // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_multimodal-one-image-prompt_streaming]
```suggestion
  // [END text_gen_multimodal_one_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_multimodal-multi-image-prompt]
```suggestion
  // [START text_gen_multimodal_multi_image_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +          // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_multimodal-multi-image-prompt]
```suggestion
  // [END text_gen_multimodal_multi_image_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_multimodal-multi-image-prompt_streaming]
```suggestion
  // [START text_gen_multimodal_multi_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +          // The Gemini 1.5 models are versatile and work with both text-only and multimodal prompts
```suggestion
          // Specify a Gemini model appropriate for your use case
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_multimodal-multi-image-prompt_streaming]
```suggestion
  // [END text_gen_multimodal_multi_image_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_multimodal-video-prompt]
```suggestion
  // [START text_gen_multimodal_video_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_multimodal-video-prompt]
```suggestion
  // [END text_gen_multimodal_video_prompt]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [START text_gen_multimodal-video-prompt_streaming]
```suggestion
  // [START text_gen_multimodal_video_prompt_streaming]
```

2024-06-23 16:56 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  // [END text_gen_multimodal-video-prompt_streaming]
```suggestion
  // [END text_gen_multimodal_video_prompt_streaming]
```

2024-06-24 15:47 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  // [START chat]
;;; Type C-c C-c to include your comment locally 
;;; After that check the transient menu (press r) to see possible actions 

I was also unsure, but I decided against it because even if we include
the `suspend` function declaration in the snippets, we would keep the
current mention, for clarity. 

In that scenario:

- Those who know coroutines will very likely have to remove the
  function declaration when copying the code, as they know where to
  put it.

- Those who *don't* know will copy the code as function, but will get
  the same error when trying to call the function as they would do
  now, as the call has to be in the correct coroutine context.

2024-06-24 15:54 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +          // [START_EXCLUDE]
In the original snippet that function declaration was not included (only the ellipsis comment above), so I decided to keep it that way.

That being said, since it's 2 lines, we can probably just include all and remove the ellipsis comment above.

wdyt?

2024-06-24 16:34 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  // [START chat]
That makes sense to me.

We'll have to make this consideration lang-by-lang probably?  And document it as part of what's expected for each language.

2024-06-24 16:49 UTC, rachelsaunders requested changes

2024-06-24 16:49 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  print(response.text)
**QUESTION**

I _think_ I read a comment from Rosário that `print` is kinda a weird thing for Android devs?

Is this something that we should figure out as part of this PR?  Specifically, does the code within the region tags need to show appropriate handling of the response?  And if so, do we do that right now in all the snippets within this PR?

Whatever we decide, we should also note it in the guidelines for how to write a good region-tagged snippet.

2024-06-24 16:49 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/java/chat.java
> +          // [START_EXCLUDE]
ya, I think that since this snippet is already so long, a few more lines won't tip the scales :-)

Let's include these lines if you think it makes sense for Android devs to see these lines.  I'll leave it up to you.

2024-06-24 16:49 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +          // Access your API key as a Build Configuration variable (see "Set up your API key" above)
**QUESTION**

Within all these snippets, we say `(see "Set up your API key" above)`, but "above" in this GitHub file, there isn't anything about the API key setup :-/

Should we maybe put a commented out line or two at the top of each file that describes how to set up your API key or that points to the "getting started" docs for setting up your API key?  https://ai.google.dev/gemini-api/docs/quickstart?lang=android#set-up-api-key

Whatever we decide, we should also note it in the guidelines for how to write a good region-tagged snippet and its file.

2024-06-24 21:32 UTC, MarkDaoust commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +  // [START tokens_multimodal_image_inline]
END

2024-06-24 21:53 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  print(response.text)
Rosário's comment is on point, `print` is never actually used in Android code. It works, absolutely, but it will be really weird for an actual app to have a `print` call in it.

That being said, I can't think of a better way of communicating the idea of "the data you want is in here". An actual app would further process the data, or store it, or show it to the user in the UI, but none of those alternatives are feasible in a short snippet. Also, how to include better error handling without making the snippet too complicated is another topic to be discussed.

My suggestion would be to move forward with this approach while we think a better one, and, if necessary, make the change in a follow up PR.

2024-06-24 22:05 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/count_tokens.kt
> +  // [START tokens_multimodal_image_inline]
fixed. thanks!

2024-06-26 01:00 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/system_instructions.kt
> +suspend fun systemInstructions() {
done

2024-06-26 04:20 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +          // Access your API key as a Build Configuration variable (see "Set up your API key" above)
I've removed the excludes.

About the "set up api key" instructions. I think adding a comment header that points people to the actual documentation is the right way. I've done so in all files. PTAL.

2024-06-26 22:10 UTC, andrewheard commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  val inputContent = content { text("What's in this picture?") }
Sorry if you just haven't gotten around to adding these yet, I think the examples in this file should be something like:
```
val image: Bitmap = BitmapFactory.decodeResource(context.resources, R.drawable.image)

val inputContent = content {
    image(image)
    text("What's in this picture?")
}
```
(Copied from `chat.kt`)

2024-06-27 15:53 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/text_generation.kt
> +  val inputContent = content { text("What's in this picture?") }
Absolutely! completely missed those. Thanks Andrew. Fixed

2024-07-02 18:53 UTC, rlazo commented
friendly ping @rachelsaunders

2024-07-05 17:32 UTC, thatfiredev commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  print(response.text)
> That being said, I can't think of a better way of communicating the idea of "the data you want is in here".

Some things we have tried in the past with other product's snippets:
- create a hypothetical function that we call with the response as argument
    ```kotlin
    val response = chat.sendMessage("How many paws are in my house?")
    updateUI(response.text)
    ````
-  add a TODO comment to remind the developer to display the response somewhere
   ```kotlin
    val response = chat.sendMessage("How many paws are in my house?")
    val output = response.text
    // TODO(developer): display this output in the UI
    ````

I don't mind if we make this change in a follow-up PR.

2024-07-05 17:37 UTC, thatfiredev commented on generativeai-android-sample/app/build.gradle.kts
> +    }
I think this will means Android Studio will index those files for developers building the sample app? Wouldn't that be unnecessary extra tasks for the dev who just wants to try out the sample app?

If so, is there a way we could do this conditionally? Like only include the `samples` dir if the build is running on CI or something like that.

2024-07-09 18:48 UTC, rlazo commented on generativeai-android-sample/app/build.gradle.kts
> +    }
Fixed.

I've moved the code from the `main` sourceSet to the `sample` sourceSet. Running `./gradlew app:assemble` still fails if the code in samples doesn't compile, but it doesn't show in AndroidStudio unless you manually change your variant to `sample` from the default `debug`

2024-07-09 18:54 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  print(response.text)
Sure thing, we can use either option. I like an hybrid option with, something along these lines

```
// TODO(developer): use a real function that updates your UI.
updateUI(response.text)
```

but I don't feel strongly about it.

As you said, we can do the change in a follow-up to unblock this change. Thanks!

2024-07-09 18:55 UTC, rlazo commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +          // Access your API key as a Build Configuration variable (see "Set up your API key" above)
PTAL

2024-07-11 14:30 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +          // Access your API key as a Build Configuration variable (see "Set up your API key" above)
LGTM!

2024-07-11 14:31 UTC, rachelsaunders commented on samples/src/main/java/com/google/ai/client/generative/samples/chat.kt
> +  print(response.text)
SGTM

2024-07-11 14:32 UTC, rachelsaunders approved these changes

2024-07-11 14:39 UTC, ryanwilson approved these changes
LGTM for approval

2024-07-11 14:39 UTC, merged